# Generated by Django 3.0.6 on 2021-09-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.IntegerField(default='0799143482'),
        ),
    ]
